spring.application.name=student-backend

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.nphauntlkaombpaqvjjx
spring.datasource.password=Umesh@123@@
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP connection pool settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# Hibernate/JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server & File Upload settings
server.port=8081
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB